### ISSUE TITLE
✨ 앱 설치 후 첫 실행 시 종로구를 CoreData 의 Location 으로 저장되도록 합니다. 

### ISSUE THREAD

**Issue by 2youngjun** [UrrrrKWANG/Kloudy#116]
### 문제 상황
- 앱 설치 후 첫 실행 시 종로구를 CoreData 의 Location 으로 저장되도록 합니다. 

### TODO
- [x] 앱 설치 후 첫 실행 시 종로구를 CoreData 의 Location 으로 저장되도록 합니다. 
- [x] AddLiveIndexView 의 Asset 을 추가합니다.
- [ ] AddLiveIndexView 로 메인 화면의 Location 을 Delegate 를 통해 전달합니다.
- [ ] CoreData Location 에 첫 번째 Sequence 의 기상 데이터를 요청하고 뷰에 표현합니다.
