### ISSUE TITLE
🔨 Django 백엔드 서버 개선하기

### ISSUE THREAD

**Issue by Valentino1994** [UrrrrKWANG/Kloudy#131]
### 문제 상황
- 현재 서버는 날씨 정보 요청이 들어올 때 마다 기상청 API에 요청을 보냅니다.
- 이 방식은 매번 요청과 응답을 받아오는 부하가 걸린다고 생각하여 서비스의 품질이 저하되고 있습니다.
- 이 때문에 백엔드 서버 개선을할 필요가 있습니다. 서비스 개선 방식은 아래와 같습니다.
  1. 기상청 API 데이터는 어차피 30분 단위로 갱신됨 -> 매번 요청을 보낼 필요가 없음.
  2. Django 에서 자체적으로 30분 단위로 DB를 갱신.
  3. 구르미 앱에서 요청을 받을 때 기상청 API에 요청을 보내는 것이 아니라, DB에서 이 값을 받아감.
  4. 햅삐
  
### TODO
- [x] ERD 새로 그리기
- [x] csv 파일 읽는 로직
- [x] Django 서버에 만들어 둘 DB Table 구성하기
- [x] 30분 간격으로 TimeInterval 하여 DB Table Update 시키는 로직
- [x] APP에서 요청이 들어왔을 때 자체 DB를 뒤져서 값을 반환하는 로직
