### ISSUE TITLE
🔨 지역 코드를 기반으로 요청 보내는 코드 만들기.

### ISSUE THREAD

**Issue by Valentino1994** [UrrrrKWANG/Kloudy#134]
### 문제 상황
- 현재 지역을 받아서 x, y를 기준으로 매번 요청을 보내고 있지만 향후 DB는 Core Data에 저장된 지역들을 지역 코드를 기반으로 요청을 보낼 예정입니다. 이에 따른 개선이 필요합니다.

### TODO
- [ ] csv 파일에 지역 이름 영문으로 넣기
- [ ] 현재 요청 시간 측정하기
- [ ] 지역코드를 갖고 있는 로컬 데이터 만들기
- [ ] MapKit을 사용 현재 지역을 기준으로 지역코드를 받아오는 로직
- [ ] 지역코드를 기반으로 날씨 정보를 보내도록 네트워크 코드 수정
