### ISSUE TITLE
:recycle: RxSwift 를 활용하여 LocationSelecationView 에서 Location SearchBar 에서 발생하는 이벤트를 주시합니다.

### ISSUE THREAD

**Issue by 2youngjun** [UrrrrKWANG/Kloudy#142]
### 문제 상황
- 기존 LocationSelectionViewController 의 코드 길이가 길어지고, 비대해져 가독성이 떨어지는 이슈가 밞생했습니다.
- 이에 SeachBar 파일을 분리하고, RxSwift 를 활용하여 LocationSelecationView 에서 Location SearchBar 에서 발생하는 이벤트를 주시합니다.

### TODO
- [x] LocationSelectionView 에서 LocationSearchBar 를 다른 파일로 분리하고, Layout 을 다시 구현합니다.
- [x] RxSwift 를 통해 LocationSearchBar 에서 방출되는 이벤트의 value 를 ViewController 인 LocationSelectionView 가 구독할 수 있도록 구현합니다.
- [x] LocationSearchBar 에서 이벤트를 통해 방출되는 value 는 다음과 같습니다. (Search 시작, Search 종료, SearchBar 의 Text String) 
- [x] LocationSelectionView 에서 subscribe 한 value 를 통해 도시 정보를 나타내는 tableView 를 그립니다.
