### ISSUE TITLE
💄  WeatherIndexDetailView 의 Layout 을 구현합니다.

### ISSUE THREAD

**Issue by 2youngjun** [UrrrrKWANG/Kloudy#155]
### 문제 상황
- WeatherIndexDetailView 의 레이아웃을 구현합니다.

### TODO
- [x] Pop Up 되는 형식으로 ViewController 가 present 되도록 구현
- [x] 3rd party library 인 Charts 를 활용하여 더미 데이터에 대한 차트 레이아웃 그리기
- [x] API 요청 후 받은 데이터를 바로 전달할 수 있도록 Rx 로 연결
