### ISSUE TITLE
✨세팅 페이지를 만들어야합니다.

### ISSUE THREAD

**Issue by Valentino1994** [UrrrrKWANG/Kloudy#180]
### 문제 상황
- 세팅 페이지를 만들어야합니다.

### TODO
- [x] 기본 레이아웃 잡기 (네비게이션 뷰, 스위치)
- [x] 버전 정보 관리하기
- [x] 위치 정보 동의받기
