### ISSUE TITLE
✨ Feat : Django - API Server - RESTful 통신

### ISSUE THREAD

**Issue by Valentino1994** [UrrrrKWANG/Kloudy#2]
### 문제 상황
- URL로 요청하면 JSON 파일 반환하는 view 함수 제출

### TODO
- [x] App에서 요청보내는 코드 만들기
- [x] urls.py 만들기
- [x] views.py 만들기
- [x] WeatherModel 만들기
- [x] MainModel 만들기
- [x] WeatherIndexModel 만들기
- [x] Serializer 만들기
- [x] API Call해서 원하는 값으로 반환해주는 함수 만들기
