### ISSUE TITLE
✨ 런치스크린이 끝나기 전 데이터를 받아서 저장하는 로직

### ISSUE THREAD

**Issue by Valentino1994** [UrrrrKWANG/Kloudy#201]
### 문제 상황
- 현재 다양한 뷰에서 사용하는 지역별 날씨 정보를 담아오는 로직이 없습니다. 이에 따라 런치스크린이 끝나기 전 데이터를 Fetch해서 AppDelegate에 저장하는 로직을 만들 필요가 있습니다.

### TODO
- [x] 런치스크린 연결하기
- [x] 코어데이터에서 지역 정보 받아오기
- [x] 지역 정보를 토대로 날씨 정보 받아서 저장하기
- [x] 위치 정보 동의를 했으면 현재 위치도 값을 받아와서 같이 넘김.
- [x] 저장이 끝난 후 런치스크린에서 메인 화면으로 넘어가기
- [x] 메인 화면에서 잘 넘어와졌는지 확인.
