### ISSUE TITLE
💄 WeatherDetailIndexView 의 Label 프로퍼티들의 설정 사항을 수정합니다.

### ISSUE THREAD

**Issue by 2youngjun** [UrrrrKWANG/Kloudy#214]
### 문제 상황
- WeatherDetailIndexView 의 Label 프로퍼티들의 설정 사항을 수정합니다.

### TODO
- [x] WeatherDetailIndexView 에 변경된 font 및 Color 을 적용합니다.
- [x] IndexStepView 의 행간 길이를 조정합니다.
- [x] Lottie/Image 및 지수 설명 문구를 수정하였습니다.
