### ISSUE TITLE
🩹 WeatherIndexView collectionView layer, UI 디테일, 코드  수정

### ISSUE THREAD

**Issue by Byeonjinha** [UrrrrKWANG/Kloudy#221]
### 문제 상황
- 뷰 전체 디테일이 hifi와 미세하게 다릅니다. 
- collectionView layer에 오류가 있습니다.
- collectionView cell이 따로 구분되어 있지않습니다.

### TODO
- [x] 뷰 전체 디테일 hifi 일치화하기
- [x] collectionView layer 디버깅 후 수정
- [x] collectionView cell 파일 새로 작성 후 컴포넌트화
