### ISSUE TITLE
✨ CheckWeatherView에서 DetailWeatherView로 location 데이터 전달

### ISSUE THREAD

**Issue by Byeonjinha** [UrrrrKWANG/Kloudy#230]
### 문제 상황
- CheckWeatherView에서 DetailWeatherView로 location 데이터 전달 합니다.

### TODO
- [x]  CheckWeatherView에서 DetailWeatherView로 location 데이터 전달
- [x] 일간 컬렉션뷰 데이터 연결
- [x] 주간 컬렉션뷰 데이터 연결
