### ISSUE TITLE
✨ WeatherIndexView 내의  indexCollectionView CoreData 로직 구현 및 세부사항 조정

### ISSUE THREAD

**Issue by Byeonjinha** [UrrrrKWANG/Kloudy#232]
### 문제 상황
- indexCollectionView 의 지수 위치 이동시 CoreData 에 저장하는 로직이 필요
- 지수 터치시 강수일 경우만 라벨이 뜨도록 UI 구현
- WeatherIndexView에 날씨 데이터 연결 해야함
### TODO
- [x] 지수 위치 이동시 CoreData 에 저장하는 로직 구현하기
- [x] 지수 터치시 강수일 경우만 라벨이 뜨도록 UI 구현하기
- [x] WeatherIndexView에 날씨 데이터 연결
