### ISSUE TITLE
✨ Feat : Django - Notification Server - Model 만들기

### ISSUE THREAD

**Issue by Valentino1994** [UrrrrKWANG/Kloudy#3]
### 문제 상황
- Notification 정보를 저장할 Model 만들기

### TODO
- [ ] models.py 만들기
- [ ] urls.py 만들기
- [ ] views.py 만들기
