### ISSUE TITLE
🐛 출시 전 발생하는 버그를 수정합니다.

### ISSUE THREAD

**Issue by 2youngjun** [UrrrrKWANG/Kloudy#311]
### 문제 상황
- 출시 전 발생하는 버그를 수정합니다.

### TODO
- [x] AppDelegate 와 RootViewController 인 ViewController 에서 두 번 날씨 정보를 요청하고 있습니다.
- [x] 위치 정보 동의를 받았을 때, 현재 위치에 대한 날씨 정보를 요청하고, CheckWeatherView 의 첫번째 ViewController 에 전달받은 날씨 정보 데이터를 표현해야합니다.
- [x] Archive 시 Upload 가 되지 않는 이슈가 있습니다.
- [x] 앱스토어에 표현되는 이름과 디바이스에 표현되는 이름이 다릅니다.
