### ISSUE TITLE
✨ 위치 정보 동의가 되어 있는 경우와 되어 있지 않은 경우에 대한 Cell 의 특성을 분기 처리합니다.

### ISSUE THREAD

**Issue by 2youngjun** [UrrrrKWANG/Kloudy#324]
### 문제 상황
- 위치 정보 동의가 되어 있는 경우와 되어 있지 않은 경우에 대한 Cell 의 특성을 분기 처리합니다.

### TODO
1. 위치 정보 동의가 되어 있는 경우
- [x] 현재 위치에 대한 기상 데이터가 들어오도록 구현

2. 위치 정보 동의가 되어 있지 않은 경우
- [x] 첫번째 Cell 의 경우 삭제가 불가능하도록 설정(첫 번째 지역마저 삭제하면 메인 화면에 아무런 기상 정보가 들어있지 않기 때문이다.)
- [x] "위치 동의 >" 버튼을 눌렀을 시 설정 뷰로 이동하도록 구현
