### ISSUE TITLE
:lipstick: WeatherIndexView 세부 수정

### ISSUE THREAD

**Issue by Byeonjinha** [UrrrrKWANG/Kloudy#335]
### 문제 상황
- 세세한 디자인 상황 수정이 필요합니다.

### TODO
- [ ] Circle 내 Shadow 삽입하기
- [ ] Image Assets 변경하기
- [ ] cell 이미지 사이즈 고정하기
