### ISSUE TITLE
✨ 유저의 현재 위치 정보 수집 권한이 설정 또는 설정되지 않았을 때 / 변경했을 때 대한 데이터 플로우와 뷰의 레이아웃을 구현합니다.

### ISSUE THREAD

**Issue by 2youngjun** [UrrrrKWANG/Kloudy#346]
### 문제 상황
- 유저의 현재 위치 정보 수집 권한이 설정 또는 설정되지 않았을 때 / 변경했을 때 대한 데이터 플로우와 뷰의 레이아웃을 구현합니다.

### TODO
1. 현재 위치 정보 수집 권한이 설정 또는 설정되지 않았을 때에 대한 분기 처리
- [x] 현재 위치 정보 수집 권한이 설정되었을 때 서버에 현재 위치 기상 데이터를 요청하고, 이를 CoreData 에 저장된 Location 기상 데이터와 함께 메인 뷰로 전달합니다. 
- [x] 현재 위치에 대한 지수 순서가 변경되었을 때 이를 로컬에 저장하기 위해 현재 위치의 indexArray 를 UserDefaults 에 저장합니다.

2. 현재 위치 정보 수집 권한 변경 시
- [x] 유저가 현재 위치 정보 수집 권한을 변경하였을 경우 이를 감지할 수 있어야 하며 메인 뷰가 Appear 되기 전에 아래와 같이 구현해야합니다.
- [x] Off 으로 변경 시 : CheckWeatherView 의 weathers 의  0번째 데이터를 remove 해야합니다.
- [x] On 으로 변경 시 : 서버에 현재 위치에 대한 기상 정보를 요청하고, 이를 CheckWeatherView 의 weathers 의 0번째에 insert 해야 합니다.
