### ISSUE TITLE
🐛 아이폰SE을 위한 오토레이아웃 임시 대응

### ISSUE THREAD

**Issue by dkdo1406** [UrrrrKWANG/Kloudy#376]
### 문제 상황
- 아이폰SE에서 메인 페이지가 제대로 안보이는 문제
- 오토레이아웃 대응 필요

### TODO
- [x] 지수 뷰 오토레이아웃으로 바꾸기
- [x] 일교차지수 오토레이아웃으로 바꾸기
- [x] 일교차지수를 첫번빼 index로 지정했을 때 바로 차트 안나타는 문제 해결하기
