### ISSUE TITLE
🩹 DetailWeatherView 세부사항 수정

### ISSUE THREAD

**Issue by Byeonjinha** [UrrrrKWANG/Kloudy#379]
### 문제 상황
- 현재 날씨 온도 맞지 않는 이슈
- 주간 날씨의 텍스트 수정 '지금 -> 오늘' 
- 주간 날씨의 오토레이아웃 수정

### TODO
- [x] 현재 날씨 온도 맞지 않는 이슈 해결
- [x] 주간 날씨의 텍스트 수정하기 
- [x]  detailWeatherView 에서 주간 텍스트 크기가 줄어들던 이슈 해결

**Comment by Byeonjinha** [comment]
detailWeatherView 에서 텍스트 크기가 줄어들던 이슈를 발견해 수정하고 닫도록 하겠습니다.
