### ISSUE TITLE
🐛 WeatherKit으로 바뀌고 나서 생긴 버그들 수정

### ISSUE THREAD

**Issue by Valentino1994** [UrrrrKWANG/Kloudy#386]
### 문제 상황
- WeatherKit으로 바꾸고 나서 버그들이 생겼습니다.

### TODO
- [x] Hourly 첫번째만 들어가는 버그
- [x] Hourly 가 0번 인덱스가 현재시간이 아니였던 버그
- [x] 바람속도 풍속을 m/s로 바꿈
