### ISSUE TITLE
✨ 서버로부터 전달 받은 데이터 가공하여 마스크, 빨래, 겉옷 지수 차트 구현

### ISSUE THREAD

**Issue by 2youngjun** [UrrrrKWANG/Kloudy#397]
### 문제 상황
- 서버로부터 전달 받은 데이터 가공하여 마스크, 빨래, 겉옷 지수 차트 구현

### TODO
- [x] 뺄래 지수 상세 뷰에 그려질 시간 별 습도 차트를 구현합니다.
- [x] 현재 시간으로 차트 x축 라벨을 변경합니다.
- [x] IndexButton 의 크기를 조정합니다.
- [x] LocationSelectionView 에서 위치 동의 버튼 탭 시 설정 뷰로 이동 중첩 버그를 수정합니다.
- [x] 온도별 차트와 강수량&습도 차트 색상을 변경합니다.
