### ISSUE TITLE
✨ Feat : Core Data - Location 구현하기

### ISSUE THREAD

**Issue by Valentino1994** [UrrrrKWANG/Kloudy#5]
### 문제 상황
- Location, Widget 만들기

### TODO
- [ ] Widget Size Enum으로 만들기
- [x] Core Data 테이블 만들기
- [x] Core Data CRUD 파일로 구현해서 꺼내쓸 수 있도록 만들기.

**Comment by Valentino1994** [comment]
Size는 Enum으로 만들 수 없었음.
