### ISSUE TITLE
💄 Feat: View - CheckWeatherCellLabelView 구현

### ISSUE THREAD

**Issue by Byeonjinha** [UrrrrKWANG/Kloudy#68]
### 문제 상황
- CheckWeatherCellLabelView의 UI를 구현한다. 

### TODO
- [ ] todayIndex 오늘의 생활 지수 라벨 추가하기
- [ ] addButton 추가 버튼 추가하기
- [ ] separatorView 구분 선 뷰 추가하기
