### ISSUE TITLE
✨ LocationSelectionView 의 CityInformation.csv 파일을 파싱한 데이터를 UISearchBar 와 함께 TableView 를 표현합니다.

### ISSUE THREAD

**Issue by 2youngjun** [UrrrrKWANG/Kloudy#78]
### 문제 상황
- LocationSelectionView 의 SearchBar 와 TableView 를 구현합니다.

### TODO
- [x] LocationSelectionView 의 SearchBar UI 구현
- [x] LocationSelectionView 의 TableView 구현
- [x] CityInformation.csv 파일을 파싱한 데이터를 UISearchBar 와 함께 TableView 를 표현
